### PR TITLE
Fix #334 wrong port config generated

### LINKED ISSUE #334: Bug: docker: Invalid port config generated if port contains '80'
## Description
Invalid port config generated if port contains '80'.

For example, if set env.WEBPORT = 8001, according to file: https://github.com/librespeed/speedtest/blob/99edf0f5f440320fb23d222b3d56b172a61d32d3/docker/entrypoint.sh#L56 , after the first start, port in config is replaced with 8001 (original is 80); But after the second, the third, ... port in config will becomes 8001010101010101.

## Server
Nothing special, just docker start with default envs (exclude WEBPORT).

## Client
Irrelvant.

## Steps to reproduce
See description.

## Expected behaviour
See description.

## Screenshots

截屏2020-07-12下午6 54 45

### PR DESCRIPTION
**Pull request by Senorsen**
Please see #334

### CODE REVIEW

File: docker/entrypoint.sh [hunk 1]
```diff
@@ -53,7 +53,7 @@ fi
 
 # Allow selection of Apache port for network_mode: host
 if [ "$WEBPORT" != "80" ]; then
-  sed -i "s/80/$WEBPORT/g" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
+  sed -i "s/^Listen 80\$/Listen $WEBPORT/g" /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
```
Comment (Senorsen) [inline docker/entrypoint.sh:56]:
```suggestion
  sed -i "s/^Listen 80\$/Listen $WEBPORT/g" /etc/apache2/ports.conf
  sed -i "s/*:80>/*:$WEBPORT>/g" /etc/apache2/sites-available/000-default.conf 
```

**Comment by adolfintel** [comment]
Thank you :)
